declare const spacing: {
    spacing0: number;
    spacing1: number;
    spacing2: number;
    spacing4: number;
    spacing6: number;
    spacing8: number;
    spacing12: number;
    spacing16: number;
    spacing20: number;
    spacing24: number;
    spacing28: number;
    spacing32: number;
    spacing40: number;
    spacing48: number;
    spacing56: number;
    spacing64: number;
    spacing72: number;
    spacing80: number;
    spacing96: number;
    spacing112: number;
    spacing120: number;
    spacing128: number;
    spacing160: number;
    spacing192: number;
    spacing200: number;
    spacing320: number;
};
export default spacing;
