import palette from '../../../foundation/palette';

const textColor = {
  'text/primary': palette.orange500,
  'text/accent/blue': palette.blue400,
  'text/accent/green': palette.lime400,
  'text/accent/yellow': palette.yellow400,
  'text/accent/red': palette.red400,
  'text/weak': palette.gray600,
  'text/neutral/subtlest': palette.gray500,
  'text/neutral/subtler': palette.gray400,
  'text/neutral/subtle': palette.gray200,
  'text/neutral': palette.gray50,
  'text/inverse': palette.white,
  'text/inverse/subtle': palette.gray700,
  'text/inverse/subtler': palette.gray600,
  'text/disabled': palette.gray500,
  'text/success': palette.lime400,
  'text/warning': palette.yellow400,
  'text/danger': palette.red400,
  'text/selected': palette.gray50,
} as const;

const bgColor = {
  'bg/secondary': palette.orange900,
  'bg/secondary/hovered': palette.orange700,
  'bg/secondary/pressed': palette.orange700,
  'bg/primary': palette.orange400,
  'bg/primary/hovered': palette.orange200,
  'bg/primary/pressed': palette.orange200,
  'bg/primary/disabled': palette.orange800,

  'bg/neutral/subtlest': palette.transparent,
  'bg/neutral/subtlest/hovered': palette.gray900,
  'bg/neutral/subtlest/pressed': palette.gray900,
  'bg/neutral/subtler': palette.transparent,
  'bg/neutral/subtler/hovered': palette.gray800,
  'bg/neutral/subtler/pressed': palette.gray800,
  'bg/neutral/subtle': palette.gray900,
  'bg/neutral/subtle/hovered': palette.gray700,
  'bg/neutral/subtle/pressed': palette.gray700,
  'bg/neutral': palette.gray800,
  'bg/neutral/hovered': palette.gray600,
  'bg/neutral/pressed': palette.gray600,
  'bg/neutral/bold': palette.gray200,
  'bg/neutral/bold/hovered': palette.gray50,
  'bg/neutral/bold/pressed': palette.gray50,
  'bg/neutral/bolder': palette.gray50,
  'bg/neutral/bolder/hovered': palette.white,
  'bg/neutral/bolder/pressed': palette.white,

  'bg/disabled': palette.gray800,
  'bg/disabled/subtlest': palette.transparent,

  'bg/input': palette.darkGray,

  'bg/accent/blue/subtlest': palette.blue900,
  'bg/accent/green/subtlest': palette.lime900,
  'bg/accent/yellow/subtlest': palette.yellow900,
  'bg/accent/red/subtlest': palette.red900,
  'bg/accent/red/subtle': palette.red500,
  'bg/accent/red': palette.red400,
  'bg/accent/gray/subtlest': palette.gray700,

  'bg/selected/primary': palette.orange400,
  'bg/selected': palette.gray50,
  'bg/selected/subtle': palette.gray800,

  'bg/inverse': palette.white,
  'bg/inverse/subtlest': palette.white10A,

  'bg/success': palette.lime900,
  'bg/success/bold': palette.lime400,

  'bg/warning': palette.yellow900,
  'bg/warning/bold': palette.yellow400,

  'bg/danger': palette.red900,
  'bg/danger/bold': palette.red500,
  'bg/danger/bold/hovered': palette.red300,
  'bg/danger/bold/pressed': palette.red300,
} as const;

const borderColor = {
  'border/neutral/subtle': palette.gray900,
  'border/neutral': palette.gray800,
  'border/neutral/bolder': palette.gray700,
  'border/input': palette.gray800,
  'border/inverse': palette.white10A,
  'border/selected': palette.gray50,
  'border/disabled': palette.gray900,
  'border/primary': palette.orange400,
  'border/hovered': palette.blue600,
  'border/focused': palette.blue400,
  'border/danger': palette.red400,
  'border/success': palette.lime400,
  'border/accent/blue': palette.blue400,
} as const;

const iconColor = {
  'icon/neutral': palette.gray600,
  'icon/neutral/bold': palette.gray500,
  'icon/neutral/bolder': palette.gray200,
  'icon/accent/gray': palette.gray50,
  'icon/accent/blue/subtle': palette.blue700,
  'icon/accent/blue': palette.blue400,
  'icon/accent/blue/bold': palette.blue200,
  'icon/accent/green': palette.lime400,
  'icon/accent/yellow': palette.yellow400,
  'icon/accent/red': palette.red400,
  'icon/inverse': palette.gray900,
  'icon/disabled': palette.gray600,
  'icon/disabled/subtler': palette.gray700,
  'icon/selected/primary': palette.orange400,
  'icon/selected': palette.gray50,
  'icon/primary/subtle': palette.orange600,
  'icon/primary': palette.orange400,
  'icon/primary/bold': palette.orange200,
  'icon/success': palette.lime400,
  'icon/warning': palette.yellow400,
  'icon/danger': palette.red400,
} as const;

const linkColor = {
  'link': palette.blue400,
  'link/hovered': palette.blue200,
  'link/pressed': palette.blue200,
  'link/neutral': palette.gray400,
  'link/neutral/hovered': palette.gray200,
  'link/neutral/pressed': palette.gray200,
  'link/neutral/bold': palette.gray200,
  'link/neutral/bold/hovered': palette.gray50,
  'link/neutral/bold/pressed': palette.gray50,
  'link/disabled': palette.gray500,
} as const;

const dimColor = {
  dim: palette.black60A,
} as const;

const scaleColor = {
  'scale/violet/0': palette.violet900,
  'scale/violet/1': palette.violet800,
  'scale/violet/2': palette.violet700,
  'scale/violet/3': palette.violet600,
  'scale/violet/4': palette.violet500,
  'scale/violet/5': palette.violet400,
  'scale/violet/6': palette.violet300,
  'scale/violet/7': palette.violet200,
  'scale/violet/8': palette.violet100,
  'scale/violet/9': palette.violet50,

  'scale/gray/0': palette.gray900,
  'scale/gray/1': palette.gray800,
  'scale/gray/2': palette.gray700,
  'scale/gray/3': palette.gray600,
  'scale/gray/4': palette.gray500,
  'scale/gray/5': palette.gray400,
  'scale/gray/6': palette.gray300,
  'scale/gray/7': palette.gray200,
  'scale/gray/8': palette.gray100,
  'scale/gray/9': palette.gray50,

  'scale/blue/0': palette.blue900,
  'scale/blue/1': palette.blue800,
  'scale/blue/2': palette.blue700,
  'scale/blue/3': palette.blue600,
  'scale/blue/4': palette.blue500,
  'scale/blue/5': palette.blue400,
  'scale/blue/6': palette.blue300,
  'scale/blue/7': palette.blue200,
  'scale/blue/8': palette.blue100,
  'scale/blue/9': palette.blue50,

  'scale/green/0': palette.green900,
  'scale/green/1': palette.green800,
  'scale/green/2': palette.green700,
  'scale/green/3': palette.green600,
  'scale/green/4': palette.green500,
  'scale/green/5': palette.green400,
  'scale/green/6': palette.green300,
  'scale/green/7': palette.green200,
  'scale/green/8': palette.green100,
  'scale/green/9': palette.green50,

  'scale/pink/0': palette.fuchsiaPink900,
  'scale/pink/1': palette.fuchsiaPink800,
  'scale/pink/2': palette.fuchsiaPink700,
  'scale/pink/3': palette.fuchsiaPink600,
  'scale/pink/4': palette.fuchsiaPink500,
  'scale/pink/5': palette.fuchsiaPink400,
  'scale/pink/6': palette.fuchsiaPink300,
  'scale/pink/7': palette.fuchsiaPink200,
  'scale/pink/8': palette.fuchsiaPink100,
  'scale/pink/9': palette.fuchsiaPink50,

  'scale/skyblue/0': palette.skyBlue900,
  'scale/skyblue/1': palette.skyBlue800,
  'scale/skyblue/2': palette.skyBlue700,
  'scale/skyblue/3': palette.skyBlue600,
  'scale/skyblue/4': palette.skyBlue500,
  'scale/skyblue/5': palette.skyBlue400,
  'scale/skyblue/6': palette.skyBlue300,
  'scale/skyblue/7': palette.skyBlue200,
  'scale/skyblue/8': palette.skyBlue100,
  'scale/skyblue/9': palette.skyBlue50,

  'scale/red/0': palette.indianRed900,
  'scale/red/1': palette.indianRed800,
  'scale/red/2': palette.indianRed700,
  'scale/red/3': palette.indianRed600,
  'scale/red/4': palette.indianRed500,
  'scale/red/5': palette.indianRed400,
  'scale/red/6': palette.indianRed300,
  'scale/red/7': palette.indianRed200,
  'scale/red/8': palette.indianRed100,
  'scale/red/9': palette.indianRed50,

  'scale/yellow/0': palette.mustardYellow900,
  'scale/yellow/1': palette.mustardYellow800,
  'scale/yellow/2': palette.mustardYellow700,
  'scale/yellow/3': palette.mustardYellow600,
  'scale/yellow/4': palette.mustardYellow500,
  'scale/yellow/5': palette.mustardYellow400,
  'scale/yellow/6': palette.mustardYellow300,
  'scale/yellow/7': palette.mustardYellow200,
  'scale/yellow/8': palette.mustardYellow100,
  'scale/yellow/9': palette.mustardYellow50,
};

const gpaiDarkColor = {
  ...textColor,
  ...bgColor,
  ...borderColor,
  ...iconColor,
  ...linkColor,
  ...dimColor,
  ...scaleColor,
} as const;

export default gpaiDarkColor;
