import fontSize from './fontSize';
import fontWeight from './fontWeight';
import lineHeight from './lineHeight';
declare const typography: {
    lineHeight1: number;
    lineHeight2: number;
    fontWeight100: number;
    fontWeight200: number;
    fontWeight300: number;
    fontWeight400: number;
    fontWeight500: number;
    fontWeight600: number;
    fontWeight700: number;
    fontWeight800: number;
    fontWeight900: number;
    fontSize50: number;
    fontSize100: number;
    fontSize200: number;
    fontSize300: number;
    fontSize400: number;
    fontSize500: number;
    fontSize600: number;
    fontSize700: number;
    fontSize800: number;
    fontSize900: number;
    fontSize1000: number;
    fontSize1100: number;
    fontSize1200: number;
    fontSize1300: number;
};
export default typography;
export { fontSize, fontWeight, lineHeight };
